title: tcbis
description: TCBIS website
baseurl: "" # the subpath of your site, e.g. /blog or github repository name
url: "http://www.tcbis.org"


collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
